#!/bin/bash
#
# Wrapper script to enter an SQLite CLI session with the TrackX database.

# TODO: Get database name from trackx.config.js
# TODO: Document this script and its use

set -Eeuo pipefail

TRACKX_DB_DIR=/opt/trackx/var/db
TRACKX_DB_FILE=trackx.db
DOCKER_IMAGE=trackx-api

docker run \
  --rm \
  --interactive \
  --tty \
  --mount type=bind,src="$TRACKX_DB_DIR",dst=/data \
  "$DOCKER_IMAGE" sqlite3 "/data/${TRACKX_DB_FILE}"
