# https://github.com/snyk/actions/
name: Snyk
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '35 20 * * 1'
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm run build
      - run: docker build -t ci/trackx-api packages/trackx-api
      - name: Snyk check for node vulnerabilities
        uses: snyk/actions/node@d1ee3d73c6f24375d0efc597c74570b0cd08a323
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk check for docker vulnerabilities
        uses: snyk/actions/docker@d1ee3d73c6f24375d0efc597c74570b0cd08a323
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ci/trackx-api
          args: --file=Dockerfile
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
